### ISSUE TITLE
Mettre à jour vers Node LTS (20.9.0)

### ISSUE THREAD

**Issue by GabLeRoux** [saglacio/saglac.io#4]

**Comment by GabLeRoux** [comment]
On peut aussi revert ce changement et rester à 18 question de tous utiliser la même version que la prod. Et on pourrait utiliser une matrix dans le CI pour vérifier la compatibilité pour le future.

**Comment by jipiboily** [comment]
Comme tu le sens. Je n'ai pas d'opinion forte sur le sujet :)
